config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do


  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root "sessions#new"
  # get "about", to: "pages#about"
  # get "signup", to: "users#new"

  # resources :articles
  # resources :users, except: [:new]

  # get "login", to:"sessions#new"
  # post "login", to:"sessions#create"
  # delete "logout", to:"sessions#destroy"

  # mount API::Base => '/'

  mount Api::Base => '/'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/article.rb
class Article < ApplicationRecord

  validates :article_title, presence: true, length: {minimum: 5, maximum:250}
  validates :article_description, presence: true, length: {minimum: 10, maximum:1000}

  belongs_to :user
  after_create :send_notification_mail

  def send_notification_mail
    SendNewArticleEmailJob.perform_async(id)
    # .deliver_now(id)
  end
end

app/controllers/api/v1/articles.rb
module Api
  module V1
    class Articles < Grape::API

      resource 'articles' do
        helpers Api::V1::Helpers
        helpers SessionsHelper

        desc 'return all articles'
        get do
          articles = Article.all
          present articles , with: Api::V1::Entities::ArticleEntity

        end

        desc 'get article'
        get ':id' do
          article = Article.find_by(id:   params[:id])
          present article , with: Api::V1::Entities::ArticleEntity
        end

        desc "add new article"
        params do
          requires :article_title, type: String
          requires :article_description, type: String
          requires :user_id, type: Integer
        end
        post "/new" do
          new_article = create_new_article(permitted_params[:article_title], permitted_params[:article_description], permitted_params[:user_id])

          if new_article[:status] == :created
            present new_article, with: Api::V1::Entities::ArticleEntity
            { message: new_article}
          else
            error!(new_article, 422)
          end

        end

        desc "update existing article"
        params do
          requires :article_title, type: String
          requires :article_description, type: String
        end
        patch ":id/edit" do
          updated_article = update_article(params[:id] , permitted_params[:article_title], permitted_params[:article_description])
        end

        desc "delete an article"
        delete ":id/delete" do
          # if logged_in? && article_to_be_deleted.user_id == current_user
            delete_article(params[:id])
          # end
        end
      end
    end
  end
end

app/controllers/api/v1/base.rb
module Api
  module V1
    class Base < Grape::API

      mount Api::V1::Articles
      mount Api::V1::Users
      mount Api::V1::FollowerFollowing
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SessionsHelper

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @all_articles = Article.all
    # @all_articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new()
  end

  def create
    byebug
    @article = Article.create!(permit_article_params)
    # @article.user = current_user
    if @article.persisted?
      flash[:notice] = "Article created successfully !"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(permit_article_params)
      flash[:notice] = "Updated successfully!"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def permit_article_params
    params.require(:article).permit(:article_title, :article_description)
  end
end

app/views/articles/_article_actions.html.erb
  <% if logged_in? && obj.user == current_user %>
  <div class="article-actions">
    <%= link_to 'Edit', edit_article_path(obj)%>
     <%= link_to("Delete", obj, data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }) %>
    <%# <%= button_to "Delete", article_path(obj), method: :delete %>
  </div>
<% end %>

app/views/articles/_articles.html.erb
<div class="container">
  <% obj.each do |article| %>
        <p class="text-muted">
          <% if article.user %>
            by <%= link_to article.user.username, user_path(article.user) %>
          <% end %>
        </p>
        <%= link_to article_path(article) do %>
        <strong> <%= article.article_title %> </strong>
        <p> <%= article.article_description[0..100] %> </p>
      <% end %>

      <%= render 'articles/article_actions', obj: article %>
      <hr />
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<p>Errors:</p>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @article, local: true) do |form| %>

  <p><%= form.label :Title %>
    <%= form.text_field :article_title %>
  </p>

  <p><%= form.label :Description %> <br />
    <%= form.text_area :article_description, rows: 15, cols: 80 %>
  </p>


  <p><%= form.submit %>
  </p>


<% end %>

app/views/articles/edit.html.erb
<h1> Editting an article </h1>

<%= render 'form' %>

<%= link_to 'Cancel', article_path(@article) %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<div>
  <%= link_to 'Start a new article', new_article_path%>
  <br />

  <%# <%= will_paginate @all_articles %>
  <%= render 'articles', obj: @all_articles %>

</div>

app/views/articles/new.html.erb
<h1> Create a new Article </h1>

<%= render 'form' %>

<%= link_to 'Cancel', articles_path %>

app/views/articles/show.html.erb
Showing articles details

<p><strong> <%= @article.article_title %> </strong></p>
<p> <%= @article.article_description %> </p>



<div class="article-actions">
  <%= render 'article_actions', obj: @article %>
  <%= link_to 'Go Back', articles_path %>
</div>